### ISSUE TITLE
domain and codomain of bipartition

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Semigroups#146]
Originally reported by: **James East (Bitbucket: [James_East](http://bitbucket.org/James_East), GitHub: Unknown)**

---

It would be good to have functions to calculate the domain and codomain of a (bi)partition.

The domain of a bipartition a in P_n is the set

domain(a) = { x in {1,…,n} : x belongs to a transversal block of a}.  

The codomain of a is the set 

codomain(a) = { x in {1,…,n} : -x belongs to a transversal block of a}.

eg, with a = [ [1,2] , [3,4,5,-5], [6,-6], [-1,-2,-3], [-4] ],

domain(a) = [3,4,5,6]

codomain(a) = [5,6]

---
- Bitbucket: https://bitbucket.org/james-d-mitchell/semigroups/issue/147

**Comment by wilfwilson** [comment]
This was resolved by PR #256
