### ISSUE TITLE
IrredundantGeneratingSubset for a semigroup with a single repeated generator

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#160]
In `stable-2.7` and `unstable 3.0`, `IrreundantGeneratingSubset` first checks whether there is only one generator; and returns it if so. It then takes the set of generators (sorts and removes duplicates) and now continues, assuming there are at least 2 generators.

If the generating set consists of a single generator repeated multiple times, then this assumption is wrong and the function ends up failing, as below:
```
gap> S := Semigroup([Transformation([1, 1]), Transformation([1, 1])]);
<transformation semigroup of degree 2 with 2 generators>
gap> IrredundantGeneratingSubset(S);
Error, Usage: cannot create a semigroup with no generators, at /Users/Wilf/GAP/lib/semigrp.gi:570 called from
Semigroup( Difference( gens, [ x ] )
```
I'll submit a pull request to fix this.

**Comment by james-d-mitchell** [comment]
This is closed by PR #161 and #162
