### ISSUE TITLE
Green's relations for free bands

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#163]
Green's relations do not seem to be behaving correctly / fully featured for free bands. For instance, I can create this error in `unstable-3.0`:

```
gap> S := FreeBand(3);;
gap> x := S.1;;
gap> D := DClasses(S);;
gap> x in D[1];
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `EquivalenceClassRelation' on 1 arguments at /Users/Wilf/GAP/lib/methsel2.g:241 called from
EquivalenceClassRelation( C
 ) at /Users/Wilf/GAP/pkg/semigroups/gap/greens/greens-generic.gi:189
```

**Comment by james-d-mitchell** [comment]
Thanks, I was aware of this already. There is no easy fix, there are essentially lots of methods for Green's relations/classes on the free band that need to be implemented.

**Comment by james-d-mitchell** [comment]
This is resolved, so I'm closing this issue.
