### ISSUE TITLE
Bug in MatrixEntries

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#164]
`MatrixEntries` returns the set of elements contained in the matrix of a Rees (0-)matrix semigroup.

This is not documented, and so the expected behaviour is not specified.

Currently `MatrixEntries` returns `Union(Matrix(R){Columns(R)}{Rows(R)});`. The function `Union` returns a sorted list, however it is not always possible to compare certain elements with `0` (which may be a matrix entry), leading to an error:
```
gap> S := Semigroup(SymmetricInverseMonoid(2));;
gap> id := Identity(S);;
gap> R := ReesZeroMatrixSemigroup(S, [[id], [0]]);;
gap> MatrixEntries(R);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `<' on 2 arguments at /Users/Wilf/GAP/lib/methsel2.g:241 called from
Set( Concatenation( tounite )
 ) at /Users/Wilf/GAP/lib/coll.gi:2788 called from
Union( Matrix( x ){Columns( x )}{Rows( x )}
 ) at /Users/Wilf/GAP/pkg/semigroups/gap/semigroups/semirms.gi:340
```
This bug is present in `stable-2.7` and `unstable-3.0`.

I will submit a pull request to fix this problem in each branch, by calling `Unique` instead of `Union` to remove duplicates without sorting. Another option would be to always place `0` first (if present) and then sort the remaining entries (which should all be comparable, as they come from the same semigroup) and append them to the end of `[0]`.

**Comment by james-d-mitchell** [comment]
@wilfwilson I think the last thing you suggest sounds like the best idea. Sort the non-zero entries, then append them to `[0]`. Can you please amend this PR to do this?

**Comment by wilfwilson** [comment]
@james-d-mitchell I've amended the PRs as requested.
