### ISSUE TITLE
MinimalIdeal doesn't work well for very high degree but small size transformation semigroups

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Semigroups#192]
In the following example:

    S := AsSemigroup(IsTransformationSemigroup, FullPBRMonoid(2));
    MinimalIdeal(S);

GAP runs out of memory trying to create the `GraphOfRightActionOnPairs` digraph which has _O(65536 ^ 2)_ many vertices. But we know the whole semigroup structure and so shouldn't use this method in this case.

**Comment by wilfwilson** [comment]
I agree this is a big issue, but I'm not sure how to proceed.

To calculate a transformation representation of the full PBR monoid we enumerate it, but that information is not stored for the resulting transformation semigroup. That information is attached to the full PBR monoid. And as it's the transformation semigroup that you're hoping to compute with, I'm not sure what to do.

Explicitly:
```
gap> B := FullPBRMonoid(2);;
gap> S := AsSemigroup(IsTransformationSemigroup, B);;
gap> KnownAttributesOfObject(S);
[ "Size", "GeneratorsOfMagma", "GeneratorsOfMagmaWithOne",
  "MultiplicativeNeutralElement" ]
gap> KnownPropertiesOfObject(S);
[ "IsEmpty", "IsTrivial", "IsNonTrivial", "IsFinite",
  "CanEasilyCompareElements", "IsDuplicateFree", "IsAssociative",
  "IsGeneratorsOfSemigroup", "IsMonoidAsSemigroup", "IsSemigroupIdeal",
  "IsPartialPermBipartitionSemigroup", "IsPermBipartitionGroup" ]
gap> KnownPropertiesOfObject(S) = KnownPropertiesOfObject(B);
true
```
Whereas for `B`, the full PBR monoid, we know a lot more:
```
gap> KnownAttributesOfObject(B);
[ "Size", "Representative", "OneImmutable", "GeneratorsOfMagma",
  "GeneratorsOfMagmaWithOne", "MultiplicativeNeutralElement",
  "CayleyGraphSemigroup", "IsomorphismTransformationSemigroup",
  "DegreeOfPBRSemigroup", "GenericSemigroupData" ]
```
So GAP doesn't (explicitly) know the full semigroup structure of `S`, it only knows things about `B`, which it has forgotten is isomorphic to `S` by some isomorphism. How do we solve this problem?

**Comment by james-d-mitchell** [comment]
One thing that is transferred by the isomorphism is the size of a semigroup. So we could just compare the size of the semigroup to the degree * (degree - 1) / 2? If the size is less then just TryNextMethod.

**Comment by wilfwilson** [comment]
I'll sort this out soon.

**Comment by wilfwilson** [comment]
@james-d-mitchell I have implemented the change you suggested above.

I also check for the degree of the transformation semigroup (regardless of the size of the semigroup). If the degree is greater than some fixed number, we determine that the algorithm will take too long, and so we choose the next method. This requires a somewhat arbitrary decision for what that number should be.

I've gone with 10000. Binomial(10000, 2) is about 10 ^ (7.7) and is pretty big. My experiments suggest it would take 10-20 minutes to run the 'action graph' algorithm on a typical semigroup of this degree.

Do you have a better suggestion for what the number should be?

**Comment by wilfwilson** [comment]
I have addressed this in pull request #204

**Comment by wilfwilson** [comment]
@james-d-mitchell Shall we close this issue? I think so - we've addressed the fact that this method didn't terminate.

There is still the problem that the exhaustive method can be faster than the acting method - such as in the example given at the start of this issue. For best performance, when the size of an acting semigroup is known, a decision would have to be made as to which method to prefer: acting or exhaustive.

However this has nothing in particular to do with `RepresentativeOfMinimalIdeal`, and really applies to all acting semigroups methods as part of a much bigger issue. It will be difficult to resolve: the cutoff point between acting and exhaustive will presumably be different for each function, and also for each type of acting semigroup.

**Comment by james-d-mitchell** [comment]
Yes, absolutely, I meant to close this earlier when I merged the pull request.
