### ISSUE TITLE
 Partial diagram monoids

### ISSUE THREAD

**Issue by The-Beast** [gap-packages/Semigroups#194]
Here are some (probably badly implemented) definitions of partial/rook diagram monoids. eg, the "rook partition monoid" RP_n defined by Grood (2006) is also implicit in Halverson-Ram (2005), and is (isomorphic to) the submonoid of P_{n+1} consisting of all partitions with n+1 and (n+1)' in the same block. The "partial dual symmetric inverse monoid" was introduced by Kudryavtseva and Maltcev (2011), and there is also its factorisable part.

    PartialFactorisableDualSymmetricInverseMonoid := function(n)
    local gens, a, b, c, d;
    gens := GeneratorsOfMonoid(FactorisableDualSymmetricInverseSemigroup(n+1));
    a := gens[1];
    b := gens[2];
    c := gens[3];
    d := a * c * Inverse(a);
    a := a * a * b * Inverse(a);
    return InverseMonoid(a,b,c,d);
    end;

    PartialDualSymmetricInverseMonoid := function(n)
    local gens, a, b, c, d, e;
    gens := GeneratorsOfMonoid(DualSymmetricInverseMonoid(n+1));
    a := AsBipartition(gens[1]);
    b := AsBipartition(gens[2]);
    c := AsBipartition(gens[3]);
    d := AsBipartition((3,n+1)) * c * AsBipartition((1,2,n+1,3));
    e := Star(d);
    a := a * a * b * Star(a) * Star(a) * a;
    return InverseMonoid(a,b,d,e);
    end;

    RookPartitionMonoid := function(n)
    local gens, GENS, a, b, c, d, e;
    gens := GeneratorsOfMonoid(PartitionMonoid(n));
    GENS := GeneratorsOfMonoid(PartitionMonoid(n+1)); 
    a := AsBipartition(gens[1],n+1);
    b := AsBipartition(gens[2],n+1);
    c := AsBipartition(gens[3],n+1);
    d := AsBipartition(gens[4],n+1);
    e := GENS[1] * d * Star(GENS[1]);
    return RegularSemigroup(a,b,c,d,e);
    end;

**Comment by james-d-mitchell** [comment]
Thanks be to the beast for submitting this issue, we will add this in the next major release.

**Comment by The-Beast** [comment]
There are probably much better ways to define the generators but they suited my (evil) purposes fine.

Best wishes,
James.

--------------------------------------------------------------------
Dr James East
Centre for Research in Mathematics
School of Computing, Engineering and Mathematics
Western Sydney University
Room EN.1.33 Parramatta campus
Ph: +61 2 9685 9108   Fax: +61 2 9685 9557
Postal: Locked Bag 1797, Penrith NSW 2751, AUSTRALIA
--------------------------------------------------------------------

[cid:8D885678-08BD-4DD1-ADF5-E6A5D3A297CC]

**Comment by james-d-mitchell** [comment]
This is resolved in commits 5100abc, b38a251, f9fd39d
