### ISSUE TITLE
Strange behaviour with equality of R-classes

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#198]
I'm not quite sure what the problem is here, but I think it has something to do with equality checking for R-classes. This seems to affect both the 2.8 and 3.0 branches.

To demonstrate, let's create a transformation semigroup:

```
gap> gens := [
>  Transformation([1, 3, 4, 1, 5, 5, 5]),
>  Transformation([1, 4, 1, 3, 5, 5, 5]),
>  Transformation([3, 3, 1, 2, 5, 5, 5]),
>  Transformation([4, 4, 2, 3, 5, 5, 5]),
>  Transformation([1, 1, 3, 4, 5, 5, 6]),
>  Transformation([1, 2, 2]),
>  Transformation([1, 4, 3, 4]),
>  Transformation([1, 2, 4, 4])];;
gap> S := Semigroup(gens);
<transformation semigroup of degree 7 with 8 generators>
```

And let's choose D to be the D-class which contains the first 4 generators.
D contains 6 R-classes.

```
gap> D := DClass(S, gens[1]);;
gap> ForAll(gens{[1 .. 4]}, x -> x in D);
true
gap> NrRClasses(D);
6
```

The first three gens are certainly in D, so let's get their R-classes -
GAP says that they are indeed 3 distinct R-classes.

```
gap> R := List(gens{[1 .. 3]}, x -> RClass(S, x));;
gap> IsDuplicateFreeList(R);
true
```

Let's get the other R-classes... there are 6 in total in D, and 3 in R, and so there
should be 3 others. But there are 4, so something has gone wrong.

```
gap> x := Difference(RClasses(D), R);;
gap> Length(x);
4
```

In particular, the R-class of t is in both R and x, even though these two lists should be disjoint.

```
gap> t := Transformation([4, 3, 4, 1, 5, 5, 5]);;
gap> RClass(S, t) in R and RClass(S, t) in x;
true
```

**Comment by james-d-mitchell** [comment]
I was already aware of an issue with the sorting of Green's classes. I think the issue is that the representatives are compared, which does not define a total order (since the representative is not fixed, and so equal Green's classes can have distinct representatives). I will investigate further.

Here is the example I have:

    gap> S := FullTropicalMinPlusMonoid(2, 2);
    <monoid of 2x2 tropical min-plus matrices with 6 generators>
    gap> H := Set(GeneratorsOfSemigroup(S), x -> HClass(S, x));
    [ <Green's H-class: Matrix(IsTropicalMinPlusMatrix, [[0, infinity],
           [infinity, 0]], 2)>,
      <Green's H-class: Matrix(IsTropicalMinPlusMatrix, [[infinity, 0],
           [0, 0]], 2)>,
      <Green's H-class: Matrix(IsTropicalMinPlusMatrix, [[infinity, 0],
           [0, 1]], 2)>,
      <Green's H-class: Matrix(IsTropicalMinPlusMatrix, [[infinity, 0],
           [0, 2]], 2)>,
      <Green's H-class: Matrix(IsTropicalMinPlusMatrix, [[infinity, 0],
           [0, infinity]], 2)>,
      <Green's H-class: Matrix(IsTropicalMinPlusMatrix, [[infinity, 0],
           [1, infinity]], 2)>,
      <Green's H-class: Matrix(IsTropicalMinPlusMatrix, [[infinity, 0],
           [infinity, infinity]], 2)> ]

[The problem here is that there are 7 `H`-classes but there should be at most 6.]

**Comment by james-d-mitchell** [comment]
This is resolved.
