### ISSUE TITLE
SmallerDegreeTransformationRepresentation runs forever on the full transformation monoid

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Semigroups#202]
`SmallerDegreeTransformationRepresentation` and `SmallDegreeTransformationRepresentation` ought to contain some heuristics to stop them from running forever on examples which clearly don't have a representation on a smaller set. For example, if the size of a semigroup `S` is 28, then it cannot be represented as a subsemigroup of the full transformation monoid on 3 points, which has size 27.

**Comment by mtorpey** [comment]
We decided to remove these functions from `unstable-3.0`, so I'm closing this issue.
