### ISSUE TITLE
Segfault associated with the empty bipartition

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#206]
There is a line in `semiex.tst` which tests (amongst other things):
```
Size(PartialDualSymmetricInverseMonoid(0));
```
In `unstable-3.0` this causes no problems, but in my `index-period` branch, since it is a monogenic monoid, it uses the new index and period methods for `Size`. Ultimately, this causes a segfault due to the following lines:
```
gap> x := Bipartition([]);;
gap> RankOfBipartition(x * x);
Segmentation fault: 11
```
For a technical reason which Michael has figured out, this segfault was _not_ being caught by Travis - however he's developed a fix for Travis, and pushed it to `unstable-3.0`. The segfault can be caused by any of several things with `x * x`, such as `NrLeftBlocks`.

**Comment by mtorpey** [comment]
Travis (in `unstable-3.0`) now correctly handles segfaults and fails when appropriate.

**Comment by james-d-mitchell** [comment]
Believe I've resolved this now. Let's see how the test get on, and then I'll close the issue.

**Comment by james-d-mitchell** [comment]
@wilfwilson can you please check if this resolves your issue, and if so close this?

**Comment by wilfwilson** [comment]
I am happy to report that you rchanges to semigroups++ resolve the issue.
