### ISSUE TITLE
Size of an exhaustive matrix monoid over a finite field

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#210]
I have come across this problem where the size is being wrongly reported, in `unstable-3.0`:
```
gap> x := Matrix(GF(2^2),
> [[Z(2^2), 0*Z(2), 0*Z(2), 0*Z(2), 0*Z(2), 0*Z(2)],
>  [Z(2^2), 0*Z(2), 0*Z(2), 0*Z(2), 0*Z(2), 0*Z(2)],
>  [0*Z(2), Z(2)^0, 0*Z(2), 0*Z(2), 0*Z(2), 0*Z(2)],
>  [0*Z(2), 0*Z(2), Z(2)^0, 0*Z(2), 0*Z(2), 0*Z(2)],
>  [0*Z(2), 0*Z(2), 0*Z(2), Z(2)^0, 0*Z(2), 0*Z(2)],
>  [0*Z(2), 0*Z(2), 0*Z(2), 0*Z(2), 0*Z(2), 0*Z(2)]]);;
gap> S := Monoid(x, rec(generic := true));
<monoid of 6x6 matrices over GF(2^2) with 1 generator>
gap> HasIsFinite(S);
false
gap> SEMIGROUP_SIZE(GenericSemigroupData(S));
8
gap> Size(S);
8
gap> Length(Elements(S));
7
```
Some explanation:

This came up when I was coming up with an example for my "size of a monogenic semigroup/monoid" stuff. Since this is a matrix over a finite field, it should use the `IndexPeriodOfSemigroupElement` method for `Size`. However this method is not being called, since the semigroup `S` does not know that it is monogenic, which is because the immediate method for `IsMonogenicSemigroup` is not being triggered. The immediate method includes the filter `IsFinite`, and the matrix semigroup `S` does not know that it is finite at creation. I would expect `IsFinite` to be set true at creation for a semigroup of matrices over finite fields. Is this another bug, or is this as expected?

**Comment by james-d-mitchell** [comment]
I think this is probably due to some wrong hash function, I'll have to check and get back to you.
