### ISSUE TITLE
Bug in the \in method for an inverse-op L-class

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Semigroups#217]
In this example:

    S := InverseMonoid(PartialPerm([2, 3, 4, 5, 6], [1, 2, 3, 4, 5]),
    PartialPerm([1, 2, 3, 4, 5], [1, 2, 3, 4, 6]),
    PartialPerm([1, 2, 3, 4, 6], [1, 2, 3, 5, 6]),
    PartialPerm([1, 2, 3, 5, 6], [1, 2, 4, 5, 6]),
    PartialPerm([1, 2, 4, 5, 6], [1, 3, 4, 5, 6]),
    PartialPerm([1, 3, 4, 5, 6], [2, 3, 4, 5, 6]),
    PartialPerm([1, 2, 3, 4, 5, 6], [6, 5, 4, 3, 2, 1]));;
    ForAll(MaximalSubsemigroups(S), T -> IsMaximalSubsemigroup(S, T));

`false` is returned.

**Comment by wilfwilson** [comment]
This is a bug in membership testing with Green's relations, as demonstrated below (`S` is the same semigroup as defined originally in the issue):
```
gap> S := InverseMonoid(
>      PartialPerm([2, 3, 4, 5, 6], [1, 2, 3, 4, 5]),
>      PartialPerm([1, 2, 3, 4, 5], [1, 2, 3, 4, 6]),
>      PartialPerm([1, 2, 3, 4, 6], [1, 2, 3, 5, 6]),
>      PartialPerm([1, 2, 3, 5, 6], [1, 2, 4, 5, 6]),
>      PartialPerm([1, 2, 4, 5, 6], [1, 3, 4, 5, 6]),
>      PartialPerm([1, 3, 4, 5, 6], [2, 3, 4, 5, 6]),
>      PartialPerm([1, 2, 3, 4, 5, 6], [6, 5, 4, 3, 2, 1]));;
gap> D := DClasses(S)[2];;
gap> y := PartialPerm([1, 2, 3, 4, 5], [6, 5, 4, 2, 1]);;
gap> y in D;
true
gap> ForAny(LClasses(D), L -> y in L);
false
```
Note that instead if we define `S` with a different generating set, the issue disappears:
```
gap> T := InverseMonoid(
>      PartialPerm([1, 2, 3, 4, 5, 6], [6, 5, 4, 3, 2, 1]),
>      PartialPerm([1, 3, 4, 5, 6], [2, 3, 4, 5, 6]),
>      PartialPerm([1, 2, 4, 5, 6], [1, 3, 4, 5, 6]),
>      PartialPerm([1, 2, 3, 5, 6], [1, 2, 4, 5, 6]));;
gap> T = S;
true
gap> D := DClasses(T)[2];;
gap> y in D;
true
gap> ForAny(LClasses(D), L -> y in L);
true
```

**Comment by james-d-mitchell** [comment]
Ok, thanks @wilfwilson I'll reassign this to me.

**Comment by wilfwilson** [comment]
@james-d-mitchell Will you be submitting a PR to fix the stable-2.8 branch?

**Comment by james-d-mitchell** [comment]
@wilfwilson no, I don't really want to release another version from stable-2.8. What do you think?

**Comment by wilfwilson** [comment]
I think that's fair enough.

**Comment by james-d-mitchell** [comment]
@wilfwilson so can we close this issue?
