### ISSUE TITLE
Faulty InjectionPrincipalFactor method for acting D-classes

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Semigroups#218]
gap> S := AnnularJonesMonoid(6);
    <regular bipartition *-monoid of degree 6 with 2 generators>
    gap> MaximalSubsemigroups(S);
    Error, usage: the second argument <s> does not belong to the
    underlying semigroup of the first argument <R>, at /Users/jdm/gap/lib/reesmat.gi:741 called from
    RMSElement( S, lookup_rows[x![1]] ^ p.row, r[x![1]] * x![2]
      * invert( c[x![3]] ), lookup_cols[x![3]] ^ p.col
     ) at /Users/jdm/gap/pkg/semigroups/gap/semigroups/semirms.gi:745 called from
    map!.fun( elm ) at /Users/jdm/gap/lib/mapprep.gi:591 called from
    ImageElm( map, elm ) at /Users/jdm/gap/lib/mapping.gi:835 called from
    x
    ^ iso
      at /Users/jdm/gap/pkg/semigroups/gap/attributes/maximal.gi:888 called from
    func( C[i] ) at /Users/jdm/gap/lib/coll.gi:746 called from
    ...  at *stdin*:2
    you can 'quit;' to quit to outer loop, or
    you can 'return;' to continue
    brk>

**Comment by james-d-mitchell** [comment]
Same thing happens for:

    S := Semigroup(PlanarPartitionMonoid(5), AsBipartition((1,2,3,4,5)));

**Comment by wilfwilson** [comment]
This is a bug in `InjectionPrinicpalFactor` for a D-class. As shown below, the injection is mapping an element of the D-class to an element which isn't in the principal factor Rees 0-matrix semigroup:
```
gap> S := AnnularJonesMonoid(5);;
gap> x := Bipartition([[1, -1], [2, 3], [4, -2], [5, -5], [-3, -4]]);;
gap> x in S;
true
gap> D := DClass(S, x);;
gap> x in D;
true
gap> inj := InjectionPrincipalFactor(D);;
gap> R := Range(inj);;
<Rees 0-matrix semigroup 5x5 over Group([ (2,4,3) ])>
gap> G := UnderlyingSemigroup(R);
Group([ (2,4,3) ])
gap> x ^ inj;
(2,(3,4),4)
gap> x ^ inj in R;
true
gap> UnderlyingElementOfReesZeroMatrixSemigroupElement(x ^ inj) in G;
false
```

**Comment by wilfwilson** [comment]
For the second example of the bug, I have come up with the following similar explanation. When running the following code, GAP seems to enter an infinite loop trying to print the result:
```
gap> S := Semigroup(PlanarPartitionMonoid(5), AsBipartition((1,2,3,4,5)));;
gap> D := DClasses(S)[2];;
gap> x := Bipartition([[1, -1], [2, -2], [3, -3], [4, -4, -5], [5]]);;
gap> x in D;
true
gap> inj := InjectionPrincipalFactor(D);;
gap> x ^ inj;
```

**Comment by james-d-mitchell** [comment]
I'm investigating, but this error seems to arise in the normalisation part of the `InjectionPrincipalFactor` code.

**Comment by james-d-mitchell** [comment]
Hold on, no it's not in the normalisation part of the code, forget that!

**Comment by james-d-mitchell** [comment]
In fact, there is a method for `InjectionPrincipalFactor` for D-classes of acting semigroups with a note above it saying that that method is not present in stable-2.8 and so is it really needed. If that method is commented out, then everything works just fine. 

What do you think @wilfwilson should I comment it out?

**Comment by wilfwilson** [comment]
@james-d-mitchell That sounds like a reasonable solution. I'll review your PR on the matter now.
