### ISSUE TITLE
Bugs with IsIdempotentGenerated

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#253]
I've found a couple of problems with the code for `IsIdempotentGenerated`.

The main method uses `Generators(S)` rather than `GeneratorsOfSemigroup(S)`, so for ideals the incorrect answer can be returned: the generators of the ideal being idempotents has little relation to whether the semigroup itself is idempotent generated:
```
gap> S := Semigroup([Transformation([3, 2, 1]), Transformation([2, 2, 2])]);;
gap> IsIdempotentGenerated(S); # false
gap> I := SemigroupIdeal(S, IdentityTransformation);
gap> IsIdempotentGenerated(I); # true
gap> I = S; # true
```
The method for RZMS only works if the `UnderlyingSemigroup` is a group, and this is currently assumed:
```
gap> mat := [[
>  Transformation([2, 3, 1]),
>  Transformation([2, 1]),
>  Transformation([1, 2, 1])]];;
gap> R := ReesZeroMatrixSemigroup(FullTransformationMonoid(3), mat);
gap> IsIdempotentGenerated(R); # causes error
```
I'm working on a fix for these problems, but I thought it would be good to create an issue to help us with bug tracking. The first problem is present in `2.8`, but in `2.8` there is no method specified method installed which applies to Rees 0-matrix semigroups, and so the second bug only exists in the `unstable-3.0` branch.

**Comment by mtorpey** [comment]
This is fixed by pull request #254.
