### ISSUE TITLE
IsomorphismSemigroup and InverseGeneralMapping: strange behaviour

### ISSUE THREAD

**Issue by mtorpey** [gap-packages/Semigroups#267]
I'm not sure what's going on here - it may be a bug in GAP, or Semigroups, or what I'm trying to do might be invalid in some way.  If anyone can explain what's happening, I'll be very grateful.

```
gap> F := FreeMonoid(2);;
gap> M := F / [[F.2 ^ 2, F.2],
>              [F.1 ^ 3, F.1 ^ 2],
>              [F.2 * F.1 ^ 2, F.1 ^ 2],
>              [F.1 * (F.1 * F.2) ^ 2, F.1 ^ 2 * F.2 * F.1],
>              [(F.2 * F.1) ^ 2 * F.2, F.2]];;
gap> iso := IsomorphismSemigroup(IsFpSemigroup, M);;
gap> S := Range(iso);;
gap> x := S.2 * S.3 * S.2;;  
gap> x ^ InverseGeneralMapping(iso);
m1*m2*m1
gap> x ^ InverseGeneralMapping(iso);
Error, Lists Assignment: <list> must be a mutable list in
  wlist[2 * i - 1] := wlist[2 * i - 1] - 1; at /home/mtorpey/gap/lib/fpmon.gi:434 called from 
FStoFM( One( FM ), UnderlyingElement( x ) ) at /home/mtorpey/gap/lib/fpmon.gi:466 called from
map!.fun( elm ) at /home/mtorpey/gap/lib/mapprep.gi:591 called from
ImageElm( map, elm ) at /home/mtorpey/gap/lib/mapping.gi:835 called from
<function "unknown">( <arguments> )
 called from read-eval loop at *stdin*:57
you can 'return;' and ignore the assignment
```

Note that `x ^ InverseGeneralMapping(iso)` works the first time, but after that fails for some reason.

Any ideas?

**Comment by wilfwilson** [comment]
This bug occurs in GAP without the Semigroups package loaded, if we replace the line
```
gap> iso := IsomorphismSemigroup(IsFpSemigroup, M);;
```
with
```
gap> iso := IsomorphismFpSemigroup(M);
```
I suggest you close this issue and open it on [the GAP GitHub](https://github.com/gap-system/gap) instead. Perhaps include a link to this (closed) issue.

**Comment by fingolfin** [comment]
I believe this change to the GAP library fixes the issue:
```diff
--- a/lib/fpmon.gi
+++ b/lib/fpmon.gi
@@ -430,6 +430,7 @@ function(M)
     fi;

     # have to decrease each entry by one because of the identity generator
+    wlist := ShallowCopy(wlist);
     for i in [1 .. 1 / 2 * (Length(wlist))] do
       wlist[2 * i - 1] := wlist[2 * i - 1] - 1;
     od;
```

**Comment by mtorpey** [comment]
I've now [posted this on the GAP issue tracker](https://github.com/gap-system/gap/issues/1258), so I'll close this here.  Thanks Max for the suggestion - I'll try it out.

**Comment by fingolfin** [comment]
note that a similar fix is needed a few lines above (I don't have a test case to trigger it, but it's the same pattern)
