### ISSUE TITLE
Heisenbug regarding comparing fp semigroup elements

### ISSUE THREAD

**Issue by mtorpey** [gap-packages/Semigroups#274]
This shows the problem:

```gap
repeat
#T# A right congruence example
F := FreeMonoid(2);;
M := F / [[F.1 * F.2 ^ 2, F.2 ^ 2],
              [F.2 ^ 3, F.2 ^ 2],
              [F.1 ^ 4, F.1],
              [F.2 * F.1 ^ 2 * F.2, F.2 ^ 2],
              [F.2 * F.1 ^ 3 * F.2, F.2],
              [(F.2 * F.1) ^ 2 * F.2, F.2],
              [F.2 ^ 2 * F.1 ^ 3, F.2 ^ 2],
              [F.2 * (F.2 * F.1) ^ 2, F.2 ^ 2 * F.1 ^ 2]];;
cong := RightSemigroupCongruence(M, [M.1, M.2 ^ 3]);;
semicong := cong!.semicong;;
semipart := EquivalenceRelationPartition(semicong);;
elm1 := M.1 ^ cong!.iso;;
part1 := First(semipart, l -> elm1 in l);;
set1 := SortedList(part1);
until ForAny(part1, x-> not x in set1);
```

**Comment by james-d-mitchell** [comment]
I can't reproduce this, running for a couple of minutes now with no problems.

**Comment by james-d-mitchell** [comment]
And that's with reporting on and off, that I can't reproduce this.

**Comment by wilfwilson** [comment]
Just to record: I also couldn't reproduce this. However @james-d-mitchell and @mtorpey believe they have identified solved the problem. It was a bug in libsemigroups. Michael has submitted [a PR to libsemigroups](https://github.com/james-d-mitchell/libsemigroups/pull/34) that resolves this.

**Comment by mtorpey** [comment]
This is now resolved, after my libsemigroups PR that Wilf mentioned.
