### ISSUE TITLE
LatticeOfCongruences still errors

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Semigroups#309]
It looks like there is still using an assumption about the internal representation of the congruences in the `LatticeOfCongruences` code, and for whatever reason the internal representation is being used. I don't understand why in `conglatt.gi:87` you aren't calling `GeneratingPairsOfSemigroupCongruence(congs[i])` 

    gap> S := Semigroup( [ Transformation( [ 2, 1, 4, 3, 5, 2 ] ),
    >   Transformation( [ 3, 4, 1, 2, 5, 3 ] ),
    >   Transformation( [ 5, 5, 5, 5, 5, 5 ] ) ] );
    <transformation semigroup of degree 6 with 3 generators>
    gap> LatticeOfCongruences(S);
    Error, Record: '<rec>.genpairs' must have an assigned value in
      pair1 := congs[i]!.genpairs[1]
     ; at /Users/jdm/gap/pkg/semigroups/gap/congruences/conglatt.gi:87 called from
    SEMIGROUPS.PrincipalXCongruencePosetNC( S, restriction, SemigroupCongruence
     ) at /Users/jdm/gap/pkg/semigroups/gap/congruences/conglatt.gi:416 called fro\
    m
    PosetOfPrincipalCongruences( S, restriction
     ) at /Users/jdm/gap/pkg/semigroups/gap/congruences/conglatt.gi:344 called fro\
    m
    LatticeOfCongruences( S, S
     ) at /Users/jdm/gap/pkg/semigroups/gap/congruences/conglatt.gi:315 called fro\
    m
    <function "unknown">( <arguments> )
     called from read-eval loop at *stdin*:5
    you can 'return;' after assigning a value
    brk>

**Comment by mtorpey** [comment]
Yep, looks like an oversight by me.  Will fix shortly.

**Comment by james-d-mitchell** [comment]
I am fixing it
