### ISSUE TITLE
no elements.h in cloned version 

### ISSUE THREAD

**Issue by cdwensley** [gap-packages/Semigroups#338]
Just forked Semigroups from GitHub gap-packages. 
As with the issue just made on Digraphs, no mention of autogen.sh in README.md. 
make failed as follows: 
ChristoleysiMac:Semigroups christopherwensley$ make
  CXX      src/semigroups_la-pkg.lo
In file included from src/pkg.cc:29:
./src/bipart.h:24:10: fatal error: 'libsemigroups/src/elements.h' file not found
#include "libsemigroups/src/elements.h"
         ^
1 error generated.
make: *** [src/semigroups_la-pkg.lo] Error 1

**Comment by james-d-mitchell** [comment]
Why not use the released version? If you really want to use the development version, then please take a look at 

https://github.com/gap-packages/Semigroups/wiki/Quickly-getting-a-working-copy-of-Semigroups

**Comment by cdwensley** [comment]
Why?  Only because I've been told that this is how things work on GitHub: fork; clone; ready to go. 
Thanks for the link you've given - I'll give it a try.

**Comment by james-d-mitchell** [comment]
Simply because the complexity of using the released version is lower than that of using the development version, everything is included, and also because the development version may contain partially implemented, or not working things.

**Comment by cdwensley** [comment]
OK, understood.  I'll stick to the released 3.0.2 for now.
