### ISSUE TITLE
Check for presence of libsemigroups

### ISSUE THREAD

**Issue by markuspf** [gap-packages/Semigroups#353]
When building Semigroups without a copy of `libsemigroups` in the `src` folder one gets a rather unhelpful error message about a missing file (in my case `blocks.cc`).

It would be best to add a check to `configure.ac` that makes sure that `src/libsemigroups/src/semigroups.cc` (for example) is present, and if it is not prints a helpful error message.

**Comment by james-d-mitchell** [comment]
Resolved by PR #387
