### ISSUE TITLE
Add subtitle to PackageInfo.g

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/Semigroups#362]
Please add subtitle to PackageInfo.g - it is used e.g. for the right column in the list of packages at http://www.gap-system.org/Releases/index.html

https://github.com/gap-packages/Semigroups/blob/c7ce4fbda8fde23e1689c3be6ecaeaa7c0d5b2c0/PackageInfo.g#L49

**Comment by wilfwilson** [comment]
Resolved by PR #365.
