### ISSUE TITLE
Improve performance of MultiplicativeNeutralElement for ideals

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#366]
For acting ideals, the method for MultiplicativeNeutralElement currently requires (in some cases) that `GeneratorsOfSemigroup` be called on the ideal. This can be costly. @james-d-mitchell suggested in the thread of PR #364 an improved method, which:

> checks if the idempotent has trivial action on the LambdaOrb and RhoOrb of the ideal

if the `GeneratorsOfSemigroup` of the ideal are not already known.

**Comment by james-d-mitchell** [comment]
Please let me know if you are going to implement this @wilfwilson, otherwise, I might later today.

**Comment by wilfwilson** [comment]
I'll have a quick go at it now. Do you want it submitted to `master` or `stable-3.0`?

**Comment by james-d-mitchell** [comment]
stable

**Comment by james-d-mitchell** [comment]
Resolved by PR #368.
