### ISSUE TITLE
AsDigraph method for LatticeOfCongruences

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Semigroups#369]
It would be helpful to have an `AsDigraph` method for the object returned by `LatticeOfCongruences`. This can be obtained by doing

    DigraphReflexiveTransitiveClosure(Digraph(AsList(LatticeOfCongruences(S))));

which is a bit long. 

As I'm writing this, I am wondering why the return value of `LatticeOfCongruences` isn't a digraph anyway, with the vertices labelled by the congruences themselves. Maybe there is a good reason that this is not done, but I can't think what it is. Any comments @mtorpey?

**Comment by wilfwilson** [comment]
I like this idea.

**Comment by mtorpey** [comment]
I like this idea too!  I may implement it next week.
