### ISSUE TITLE
Semigroups breaks testinstall/fpmon.tst in GAP

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/Semigroups#391]
The following happens when Semigroups package is loaded:
```
gap> Test("tst/testinstall/fpmon.tst");
# line 20 of 54 (37%)terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
Aborted
```

**Comment by james-d-mitchell** [comment]
Which version please?

**Comment by james-d-mitchell** [comment]
Also which compiler and version, what version of GAP, and the config.log if you can provide it? Thanks @alex-konovalov

**Comment by alex-konovalov** [comment]
@james-d-mitchell: master branch of GAP, semigroups 3.0.6, gcc 4.8.5, and config.log as attached.

[config.log](https://github.com/gap-packages/Semigroups/files/1347541/config.log)

**Comment by james-d-mitchell** [comment]
Thanks@alex-konovalov

**Comment by james-d-mitchell** [comment]
I cannot reproduce this, `fpmon.tst` runs just fine.

**Comment by alex-konovalov** [comment]
Test passes in 64-bit build on Mac (Apple LLVM version 8.0.0 (clang-800.0.42.1). The test fails on kovacs in both 32- and 64-bit builds.  @markuspf would you be able to put some newer version of gcc there, please?

**Comment by james-d-mitchell** [comment]
What system is kovac running? @alex-konovalov ?

**Comment by alex-konovalov** [comment]
@james-d-mitchell I am afraid Semigroups also breaks `testinstall/semigrp.tst`. Could you add it to the test as well? (Since your regression tests have GAP around anyway, just loading a package and running `testinstall.g` from GAP could be a good idea).

kovacs has Scientific Linux 7.3

**Comment by james-d-mitchell** [comment]
Ok, noted. These look like harmless diffs except one, which is an error.

**Comment by ChrisJefferson** [comment]
This isn't an old compiler problem, it's a mac/linux problem. Macs always link the pthread automatically, Linux needs a flag (`-pthread`) I think.

**Comment by james-d-mitchell** [comment]
Yes, but everything works with no problems in our travis tests for Semigroups (which use Ubuntu), and -pthread is one of the compiler flags specified in the autotools setup of Semigroups. So, missing compiler/link flags is not the issue either.

**Comment by james-d-mitchell** [comment]
@alex-konovalov failing being able to update the compiler and test that, can you provide me access to kovac so that I can try to debug this there?

**Comment by alex-konovalov** [comment]
Tonight: master branch of GAP, semigroups 3.0.7, gcc 4.8.5 on reinstalled kovacs - everything works fine.

**Comment by james-d-mitchell** [comment]
Awesome, so it was an issue with the compiler in the end I guess. Thanks @alex-konovalov

**Comment by alex-konovalov** [comment]
The problem strikes back - in 32-bit builds it still persists. Let's keep it open, I will try to get newer gcc.

**Comment by james-d-mitchell** [comment]
I think this is a known bug in GCC 4.8, see:

https://stackoverflow.com/questions/19463602/compiling-multithread-code-with-g

**Comment by james-d-mitchell** [comment]
@alex-konovalov any developments on this?

**Comment by alex-konovalov** [comment]
I have asked to install some newer version of gcc. At the moment 64-bit builds pass, but 32-bit fail.

**Comment by james-d-mitchell** [comment]
@alex-konovalov does the 32-bit fail with the same error as above or something else?

**Comment by alex-konovalov** [comment]
@james-d-mitchell same error for 32-bit build. We switched to gcc 6.3.1, and the problem disappeared.
