### ISSUE TITLE
Semigroups breaking tst/testinstall/semigrp.tst and semitran.tst

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Semigroups#395]

**Comment by wilfwilson** [comment]
@james-d-mitchell I have already started (and basically finished) work on fixing the diffs in `tst/testinstall/semigrp.tst`, except for the one about congruences.

**Comment by james-d-mitchell** [comment]
I've just fixed the other error about congruences.

**Comment by james-d-mitchell** [comment]
Resolved by [GAP PR 1757](https://github.com/gap-system/gap/pull/1757)
