### ISSUE TITLE
Version mismatch in GAP 4.8.9

### ISSUE THREAD

**Issue by egri-nagy** [gap-packages/Semigroups#432]
Semigroups 3.0.7 was distributed with GAP 4.8.9, buit it requires GAP 4.9.0, so it cannot be loaded.

**Comment by james-d-mitchell** [comment]
Thanks for the report @egri-nagy, I think this is an issue for the main GAP repo though. The Semigroups developers did not intend Semigroups to be distributed with GAP 4.8.9, and it's not even the most recent version (3.0.11). I'm not sure why this happened @alex-konovalov any ideas?

**Comment by ljgly** [comment]
Semigroups (3.0.11) can not be loaded in Window, because  it cannot be compiled  in window?

**Comment by alex-konovalov** [comment]
@egri-nagy Please see https://mail.gap-system.org/pipermail/forum/2017/005635.html about version mismatch:

It happened that the GAP 4.8.9 release contains the version of
the Semigroups package which requires the coming soon GAP 4.9
release and it not usable in GAP 4.8.

Apologies for this error. If you need to use the Semigroups
package in GAP 4.8 and have already installed GAP 4.8.9, you
need to remove the directory `gap4r8/pkg/semigroups-3.0.7/`
from the GAP 4.8.9 installation, download Semigroups 2.8.0 from
https://github.com/gap-packages/Semigroups/releases/tag/v2.8.0
and unpack it in the `pkg` directory of the GAP 4.8.9 installation
(so that it will be placed in the `gap4r8/pkg/semigroups-2.8.0/`
directory).

We plan to release GAP 4.8.10 by the middle of January 2018, to
include several new package releases and a compatible version of
Semigroups.

**Comment by james-d-mitchell** [comment]
@ljgly that's news to me if it cannot be compiled on Windows, if that's so, then that's probably a separate issue to this one.

**Comment by alex-konovalov** [comment]
At least 3.0.10 does not compile on Windows:
```
Running 'make' 
  CXX      src/semigroups_la-pkg.lo
In file included from /usr/include/wchar.h:4:0,
from /usr/lib/gcc/i686-pc-cygwin/4.9.2/include/c++/cwchar:44,
from /usr/lib/gcc/i686-pc-cygwin/4.9.2/include/c++/bits/postypes.h:40,
from /usr/lib/gcc/i686-pc-cygwin/4.9.2/include/c++/iosfwd:40,
from /usr/lib/gcc/i686-pc-cygwin/4.9.2/include/c++/ios:38,
from /usr/lib/gcc/i686-pc-cygwin/4.9.2/include/c++/ostream:38,
from /usr/lib/gcc/i686-pc-cygwin/4.9.2/include/c++/iostream:39,
from src/pkg.h:26,
from src/pkg.cc:23:
/usr/include/math.h:263:24: error: â€˜double infinity()â€™ redeclared as different kind of symbol
extern double infinity _PARAMS((void));
^
In file included from src/pkg.cc:23:0:
src/pkg.h:96:12: note: previous declaration â€˜UInt** infinityâ€™
extern Obj infinity;
^
In file included from src/libsemigroups/src/report.h:35:0,
from src/libsemigroups/src/semigroups.h:33,
from src/semigrp.h:25,
from src/pkg.cc:32:
src/libsemigroups/src/timer.h: In member function â€˜bool libsemigroups::Timer::string_it(libsemigroups::Timer::nano_t&, std::string&, std::string, size_t)â€™:
src/libsemigroups/src/timer.h:128:16: error: â€˜to_stringâ€™ is not a member of â€˜stdâ€™
str += std::to_string(x.count()) + unit;
^
Makefile:586: recipe for target 'src/semigroups_la-pkg.lo' failed
make: *** [src/semigroups_la-pkg.lo] Error 1

WARNING: Failed to build semigroups-3.0.10

17 Dec 2017 09:12:08
```
I will be watching next builds to see what's happening with 3.0.11

**Comment by james-d-mitchell** [comment]
Thanks @alex-konovalov, I can see the first error is an issue. But the second one, I don't understand in `libsemigroups::Timer::string_it` the header `string` is included, and according to:

http://en.cppreference.com/w/cpp/string/basic_string/to_string

this is defined in the `string` header. Also we are running travis tests on cygwin at appveyor (only for 32 bit) so, I don't really understand this error. Can you please report what compiler etc you are using?

**Comment by james-d-mitchell** [comment]
Oh wait, I see that you are using gcc 4.9.2.

**Comment by james-d-mitchell** [comment]
hmm, this is another too old compiler issue...

**Comment by alex-konovalov** [comment]
Another trouble: now adding Semigroups 2.8.0 breaks loading all packages in stable-4.8 branch:
```
#I  AutomGrp: start loading needed/suggested/self packages
#I            automgrp
#I  AutomGrp: start reading file 'init.g'
#I  AutomGrp: finish reading file 'init.g'
#I  AutomGrp: start reading file 'read.g'
Error, <flags2> must be a flags list (not a boolean or fail) in
  <compiled or corrupted statement>  called from 
<compiled or corrupted statement>  called from
SetFilterObj( o, IsClosed 
 ); at /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest/GA\
PCOPTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovacs/GAP-pkg-update-s\
table-snapshot/pkg/semigroups-2.8.0/gap/orbits.gi:152 called from
Enumerate( o, infinity 
 ) at /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest/GAP\
COPTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovacs/GAP-pkg-update-st\
able-snapshot/pkg/orb-4.8.0/gap/orbits.gi:1045 called from
Enumerate( LambdaOrb( S ) 
 ) at /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest/GAP\
COPTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovacs/GAP-pkg-update-st\
able-snapshot/pkg/semigroups-2.8.0/gap/semigroups-acting.gi:171 called from
list[i][deg + 1] 
in semi
  at /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest/GAPC\
OPTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovacs/GAP-pkg-update-sta\
ble-snapshot/pkg/automgrp/gap/listops.gi:56 called from
...  at line 
45
  of /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-stable-quicktest/GAPC\
OPTS/64build/GAPGMP/gmp/GAPTARGET/packagesload/label/kovacs/GAP-pkg-update-sta\
ble-snapshot/pkg/automgrp/gap/groups.g
you can replace <flags2> via 'return <flags2>;'
brk> 
======OUTPUT END: LoadAllPackages with autoloaded
```
This involves AutPGrp 1.8 (25/11/2016) which is not so new calling orb 4.8.0 released by @fingolfin on 10/11/2017. Perhaps I should revert also to orb 4.7.6 (08/03/2016) which has been included in GAP 4.8.8. Will try to experiment...

**Comment by james-d-mitchell** [comment]
Ugh, we haven't changed Semigroups 2.8.0 in nearly 18 months, but I could make a release of 2.8.1 if necessary to resolve this.

**Comment by egri-nagy** [comment]
The 2.8.1 release sounds good if it is just about updating its dependencies. Currently, for SubSemi, SgpDec work we need a stable baseline. We can also stick to GAP4.8.8.

**Comment by james-d-mitchell** [comment]
@egri-nagy version 3.0.11 is stable, and usable with GAP 4.9. 

I will however try to release 2.8.1 today to resolve the last issue above.

**Comment by egri-nagy** [comment]
@james-d-mitchell Sorry, what I really meant was 'released' instead of stable. For quick installation purposes for someone who doesn't want to set it up through github.

**Comment by james-d-mitchell** [comment]
Fair enough @egri-nagy I'll see what I can do!

**Comment by egri-nagy** [comment]
@james-d-mitchell Thanks a lot!

**Comment by james-d-mitchell** [comment]
I released Semigroups v2.8.1 which ought to be compatible with GAP 4.8.9

**Comment by james-d-mitchell** [comment]
I think this resolves your issues @egri-nagy and @alex-konovalov, but not your issue @ljgly.  I'm going to suggest opening a separate issue for that.

**Comment by ljgly** [comment]
Thanks@James-d-mitchell, while I repace semigroup2.8.10 with semigroup2.8.11 in pkg.
When I type " LoadPackage("semigroups");" in GAP4.8.9 on windows, then the following 
appear:
gap> LoadPackage("semigroups");
#I  Semigroups package is not available. To see further details, enter
#I  SetInfoLevel(InfoPackageLoading,4); and try to load the package again.
fail

**Comment by jamesjer** [comment]
@ljgly, in semigroups 2.8.1, PackageInfo.g says:

Dependencies := rec(
  GAP := ">=4.9.0",
 ...
)

so GAP 4.8.9 refuses to load it.

**Comment by james-d-mitchell** [comment]
@jamesjer oops, I'll have to rectify that with another release...

**Comment by alex-konovalov** [comment]
Thanks @jamesjer for noticing this. I haven't even tried to get 2.8.1 into GAP 4.8 distribution, and now I see that it would not work anyway. 

I am going to warp and publish GAP 4.8.10 with Semigroups 2.8.0 - @james-d-mitchell if you can review https://github.com/gap-system/gap/pull/2089 to ensure that your packages are handled and described correctly, that would be helpful. Thanks!

**Comment by james-d-mitchell** [comment]
@ljgly @jamesjer @alex-konovalov I released Semigroups 2.8.2, which should work ok with GAP 4.8.10, and Orb 4.8.0, but will not be included with GAP 4.8.10 for some technical reasons.

**Comment by ljgly** [comment]
Thanks@james-d-mitchell @jamesjer;  Semigroups 2.8.2 run well with GAP 4.8.9 on windows.

**Comment by james-d-mitchell** [comment]
Can this be closed now?

**Comment by alex-konovalov** [comment]
@james-d-mitchell I think it's fine to close this now.

**Comment by alex-konovalov** [comment]
@james-d-mitchell PS: on Windows, compilation ends now as follows:
```
  CXX      src/semigroups_la-congpairs.lo
In file included from src/semigrp.h:25:0,
from src/congpairs.cc:28:
src/libsemigroups/src/semigroups.h:38:77: note: #pragma message: GCC version >=5.0 is recommended, some features may not work correctly
"GCC version >=5.0 is recommended, some features may not work correctly")
^
  CXX      src/semigroups_la-semigrp.lo
In file included from src/semigrp.h:25:0,
from src/semigrp.cc:19:
src/libsemigroups/src/semigroups.h:38:77: note: #pragma message: GCC version >=5.0 is recommended, some features may not work correctly
"GCC version >=5.0 is recommended, some features may not work correctly")
^
  CXXLD    semigroups.la
/usr/bin/mkdir -p ./bin/i686-pc-cygwin-default32 ./bin/lib
cp -R src/libsemigroups/.libs/* ./bin/lib/
cp .libs/semigroups.dll /cygdrive/c/Users/jenkins/workspace/GAP-master-windows-build/GAP-master-snapshot/pkg/semigroups-3.0.12/bin/i686-pc-cygwin-default32/semigroups.so
SUCCESS!
make[1]: Leaving directory '/cygdrive/c/Users/jenkins/workspace/GAP-master-windows-build/GAP-master-snapshot/pkg/semigroups-3.0.12'

19 Jan 2018 21:14:48
```
