### ISSUE TITLE
`scripts/make-deps.py` uses print without braces

### ISSUE THREAD

**Issue by ssiccha** [gap-packages/Semigroups#442]
I get
```
  File "scripts/make-deps.py", line 43
    print 'ERROR: can\'t find ' + name
```
when I try to run the version from current master.

**Comment by james-d-mitchell** [comment]
@ssiccha `make-deps.py` is just meant to be a helper script for developers, nothing more. All it does is run `make clean && ./configure && make` on the dependencies of Semigroups. I guess you are using an out of tree build, and so the script can't find the other packages. 

I suggest rebuilding them either manually or using the `gap/bin/BuildPackages.sh` script.

**Comment by ssiccha** [comment]
Ah shoot, I didn't copy the full error message. Our python version apparently doesn't understand a `print` statement without braces:
```
  File "scripts/make-deps.py", line 43
    print 'ERROR: can\'t find ' + name
                              ^
SyntaxError: Missing parentheses in call to 'print'
```
