### ISSUE TITLE
Seg fault when computing Green's classes of a McAlister triple

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/Semigroups#447]
Both Chris and I get a seg fault when running the following:
~~~~
gap> x := Digraph([1 .. 1000], {x, y} -> x mod y = 0);;
gap> M := McAlisterTripleSemigroup(Group(()), x, x);;
gap> Size(M);;
gap> GreensRClasses(M);
~~~~

**Comment by ChristopherRussell** [comment]
Although @flsmith has fixed the seg fault (thanks!) this example is impractical to compute due to it being a semilattice with over 500 generators!
