### ISSUE TITLE
Use full names in PackageInfo.g

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/Semigroups#504]
Would it be possible to use the first full name in `FirstNames` component in PackageInfo.g file, like the majority of packages doing? GAP website content generating scripts will still be able to convert them to initials in some places, but will display it in full in a package overview page?

This request actually comes not from the website maintenance, but from https://github.com/gap-system/gap-distribution/issues/49. Extracting names from PackageInfo.g files,  I am trying to get a list of all package authors without duplicates, and using different forms for the same person makes it more difficult. For example, we have both

 - M. Delgado, Manuel Delgado, 
 - C. Jefferson, Christopher Jefferson, 
 - J. D. Mitchell, James Mitchell, 
 - M. Pfeiffer, Markus Pfeiffer, 
 - C. Russell, Christopher Russell,

**Comment by james-d-mitchell** [comment]
Of course it's possible, I'm not completely sure I see the point, but I'm happy to accept a PR making this change.

**Comment by alex-konovalov** [comment]
PR #505 it is. For people involved in other packages, I used the same version (e.g. "James" instead of "James D." for you).
