### ISSUE TITLE
Locating specific algorithm (Schreier generator calculation)

### ISSUE THREAD

**Issue by Time0o** [gap-packages/Semigroups#506]
This is not an issue report per se but rather a simple question, I hope it is appropriate to post it here.

As part of a project I'm currently working on I require an algorithm which can efficiently perform membership tests for inverse semigroups. For a number of reasons I would like to avoid using GAP and so I've tried directly implementing the relevant algorithms from [Computing finite semigroups](https://arxiv.org/abs/1510.01868) in C++.

At the moment I am somewhat stuck and was hoping to gain some clarity by looking at this package's source code. However, I find it rather difficult to locate the relevant source code sections. In particular I am looking for the implementation of Algorithm 4 from the paper which computes Schreier generators.

It would help me greatly if someone could point me to the relevant source file(s).

**Comment by james-d-mitchell** [comment]
@Time0o Good question, it is probably not very easy to point to the exact files that do what you want. On the other hand, it is probably not too difficult to explain what you need to implement to get the methods for inverse semigroups in our paper to work. I'd be happy to correspond with you about this by email, if you want. My email address is on my webpage:

http://www-groups.mcs.st-andrews.ac.uk/~jamesm/

As a side note: I guess you are aware of [libsemigroups](https://james-d-mitchell.github.io/libsemigroups/) which is a C++ library used by the GAP package Semigroups, but does not (yet) contain the algorithms in the paper you cite. In the next version of `libsemigroups` we will likely include many of the components required to compute inverse semigroups using the algorithms in [Computing finite semigroups](https://arxiv.org/abs/1510.01868), and it ought to be more or less straightforward to include the method for inverse semigroups in the next release. On the other hand, I'm not completely sure about the timetable for the release of the next version of `libsemigroups`, I am hoping to have it released this year, but it depends.

**Comment by Time0o** [comment]
@james-d-mitchell Thank you for the extensive answer. I was not aware of `libsemigroups` which does sound very promising. However, I am not entirely sure if the GPL is a problem in my case, I will have to talk to my advisor about that. In the meantime I will continue working on my implementation, if I really hit a dead end (which seems likely, I admittedly lack the mathematical background to fully comprehend the paper) I will take you up on your offer and send an email.
