### ISSUE TITLE
Diff caused in GAP's test file testbugfix/2018-05-09-submagma.tst

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#511]
This following test, from GAP master, gives diffs when run with Semigroups loaded:
```
testing: /Users/Wilf/gap/tst/testbugfix/2018-05-09-submagma.tst
########> Diff in /Users/Wilf/gap/tst/testbugfix/2018-05-09-submagma.tst:33
# Input is:
mgm:=Magma( () );
# Expected output:
<commutative semigroup with 1 generator>
# But found:
<trivial group with 1 generator>
########
########> Diff in /Users/Wilf/gap/tst/testbugfix/2018-05-09-submagma.tst:41
# Input is:
IsMagmaWithInverses(mgm);
# Expected output:
false
# But found:
true
########
```
The first one is a minor issue, the Semigroups package immediately deduces that `mgm` is trivial so it is a group; but how about the second one? A trivial magma is of course a group in one mathematical sense, but I can imagine people complaining about these sorts of things.

**Comment by fingolfin** [comment]
@alex-konovalov just made me aware of this issue. 

The `IsMagmaWithInverses` call in line 41 is not crucial and I only added it to the test for symmetry. The crucial `IsMagmaWithInverses` tests are the other three, for empty magmas, resp. a magma with the only element `0`, for which `Inverse` is not defined.

Likewise, the printing of the magma in line 33/34 is not crucial, so an acceptable fix would be to change that line to use a double semicolon.

If you make a PR for this, I'll be happy to approve it.

**Comment by james-d-mitchell** [comment]
BTW: this is a duplicate of #492.

**Comment by wilfwilson** [comment]
Oops, sorry for the duplicate @james-d-mitchell 

@fingolfin to be clear, do you mean a PR which removes line 41 and suppresses the output of line 33? I'll do it.

**Comment by wilfwilson** [comment]
Resolved by https://github.com/gap-system/gap/pull/2796.
