### ISSUE TITLE
Extend standard test specified in PackageInfo.g

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/Semigroups#517]
This comes from the discussion at https://github.com/gap-packages/Semigroups/pull/515 - opening a new issue to make it noticeable.

Currently the only test that is specified in PackageInfo.g is `tst/testinstall.tst` which is very short. OTOH, there is a collection of tests in `tst/standard`, and a function `SemigroupsTestStandard` that runs more thorough test in two modes.

Solution 1: create a file `tst/teststandard.g`:
```
LoadPackage( "semigroups" );
TestDirectory(DirectoriesPackageLibrary( "semigroups", "tst/standard" ),
  rec(exitGAP     := true) );
FORCE_QUIT_GAP(1); # if we ever get here, there was an error
```
and replace in `PackageInfo.g`

    TestFile := "tst/testinstall.tst",

by 

    TestFile := "tst/teststandard.g",

Solution 2: Same as above, but with `tst/teststandard.g` with something along the lines (not tested)
```
LoadPackage( "semigroups" );
if SemigroupsTestStandard() then
    QUIT_GAP(0);
else
    QUIT_GAP(1);
fi;
FORCE_QUIT_GAP(1); # if we ever get here, there was an error
```
However, some scripts that I use to analyse tests output expect the magic line "#I No errors detected while testing" to appear exactly once, but `SemigroupsTestStandard` displays it twice. We had a similar situation in Profiling (https://github.com/gap-packages/profiling/issues/47). Will it be possible to tweak `SemigroupsTestStandard` in a way to please the script which checks whether tests pass or fail?

**Comment by james-d-mitchell** [comment]
I think this is now resolved via PR #525.

**Comment by wilfwilson** [comment]
It should be yes 🙂 . As @alex-konovalov suggests, I'll keep an eye on https://travis-ci.org/gap-packages/gap-docker-pkg-tests-master-devel and https://travis-ci.org/gap-packages/gap-docker-pkg-tests-stable-4.10-devel to check that his tests work properly with the new test file.

**Comment by alex-konovalov** [comment]
@wilfwilson @james-d-mitchell thanks. Note that I can't see that in those Travis tests until it will appear in the Semigroups master branch.

**Comment by wilfwilson** [comment]
I've merged it into `master` on my fork; I'll push the merge to this repo once the tests pass.

**Comment by wilfwilson** [comment]
@alex-konovalov done

**Comment by alex-konovalov** [comment]
@wilfwilson @james-d-mitchell thanks - it works!!! https://travis-ci.org/gap-packages/gap-docker-pkg-tests-stable-4.10-devel/jobs/429243580
