### ISSUE TITLE
Make a semigroup from a semilattice digraph

### ISSUE THREAD

**Issue by ChristopherRussell** [gap-packages/Semigroups#527]
It would be nice to have a function which takes a Digraph which is a `IsJoinSemilatticeDigraph` or `IsJoinSemilatticeDigraph` and returns a semilattice semigroup which is isomorphic to the semigroup of the vertices with the meet or join operation. Since semilattice are inverse semigroups this could be a semigroup of partial perms but it could also be a semigroup of transformations.

**Comment by ChristopherRussell** [comment]
Actually I have written an implementation for this and will submit it properly with docs and tests when I have time.

**Comment by james-d-mitchell** [comment]
Can you close this issue @ChristopherRussell if this is resolved??

**Comment by ChristopherRussell** [comment]
Resolved by [gap-packages/digraphs#136](https://github.com/gap-packages/Digraphs/pull/136)
