### ISSUE TITLE
Invalid (?) assumption in freeinverse.gi that an Iterator for a free group has !.word bound

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#532]
Currently, in the `stable-4.10` branch of GAP, the `tst/standard/freeinverse.tst` file fails when all packages are loaded. This is because (due to very long-standing a bug in GAP) a method for `Iterator` in RCWA that applies to certain groups ends up having higher rank than the special GAP library `Iterator` method for free groups.

The code in `Iterator` for a free inverse semigroup assumes that `Iterator` for a free group has a component `!.word`, and this presumably records something. I don't see this documented anywhere, so we probably shouldn't rely on this behaviour to exist forever. The test file currently fails because the Iterator for a free group returned by the RCWA method does not have a `!.word` component.

In the first instance, I will attempt to fix this by adding `SUM_FLAGS` to the GAP library method for `Iterator`, even though this won't be required any more when the `master` branch of GAP ends up being the version required by Semigroups.

In the second instance, we should try to make this code more robust.

**Comment by james-d-mitchell** [comment]
Just to mention that the most important point here is that we should not depend on the implementational details of free groups but rather on their documented public methods.

**Comment by wilfwilson** [comment]
Resolved by #540.

**Comment by james-d-mitchell** [comment]
Resolved in v3.0.20.
