### ISSUE TITLE
In master branch of GAP, crash happens when tests of Semigroups run with all packages loaded

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/Semigroups#550]
In master branch of GAP, crash happens when tests of Semigroups run with all packages loaded
```
Testing semigroups 3.0.20, test=/circa/scratch/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/64build/GAPTARGET/packages/label/kovacs/GAP-master-snapshot/pkg/semigroups-3.0.20/tst/teststandard.g, all packages=true
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
./testpackages.in: line 324: 32171 Done                    echo 'SetUserPreference("UseColorsInTerminal",false); RunPackageTests( "semigroups", "3.0.20", "tst/teststandard.g", "true" );'
     32172 Aborted                 (core dumped) | /circa/scratch/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/64build/GAPTARGET/packages/label/kovacs/GAP-master-snapshot/bin/gap.sh --quitonbreak -b -m 100m -o 1g -q -x 80 -r -A -L wsp.g >> dev/log/testpackages2$TIMESTAMP.semigroups
```
that does not happen with stable-4.10 branch of GAP.

**Comment by james-d-mitchell** [comment]
@wilfwilson is this resolved by PR #551 ? If so, can you please label this `resolved-pending-release`, thanks!

**Comment by wilfwilson** [comment]
As far as I am aware, this is not fixed by #551. Although I have been unable to actually reproduce this crash.

**Comment by james-d-mitchell** [comment]
How much memory does the machine running this test have @alex-konovalov ? It is always possible that we simply use too much memory, but it's odd that never came up before.

**Comment by alex-konovalov** [comment]
The machine has 64GB RAM. Also, note that GAP is started with `-o 1g` - but then if you hit it,  you'd have an diff in the test, not a crash.

**Comment by james-d-mitchell** [comment]
Ok, to be able to debug this, I'll need more details please:

1. Can you say in what line of what test it fails? 
2. What versions of what packages are in the build?

**Comment by alex-konovalov** [comment]
You can see this at https://travis-ci.org/gap-system/gap-docker-pkg-tests-master/jobs/438418879 - it fails at `semigroups-3.0.20/tst/standard/attr.tst` (the log does not show the line though - can you try manually please?) and the message says `cannot allocate memory for thread-local data: ABORT`. Packages present there can be seen in the GAP banner, and they are from the current packages-master.tar.gz archive.

**Comment by wilfwilson** [comment]
Ah, maybe I came across this problem in some form before. I have slowly been trying to change the Semigroups package (accommodating the changes to the way that methods are ranked in GAP `master`) so that GAP's tests pass when all packages are loaded.

However I've not even started trying to get the Semigroups package tests to run with all packages loaded in the GAP `master` branch. When I run `SemigroupsTestStandard();` in GAP master with all packages loaded, it hangs almost immediately in `tst/standard/attr.tst`. I've not seen an actual crash; but I've always quit before waiting very long. I assumed it was simply a case of a much slower method being applied than what we want.

**Comment by wilfwilson** [comment]
@alex-konovalov Does this crash still occur? As of today, it seems that the problems related to all packages being loaded in the GAP master branch have been resolved. In particular, Semigroups seems to work fine for me in the master branch with all packages loaded now.

**Comment by alex-konovalov** [comment]
No, works now - see e.g. https://travis-ci.org/gap-system/gap-docker-pkg-tests-master/jobs/452947860. Thanks.
