### ISSUE TITLE
The bibliography in the documentation should be updated

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#559]
Some of the references in the documentation are out of date, for instance the proper reference for the computing maximal subsemigroups paper is now available, and so is the one for the partitioned binary relations paper. It would be good if someone could check all of them and update if necessary.

I also think it is worth investigating whether we can improve the display of the bibliography. Things like `Ara{\'u}jo` are appropriate for actual bibTeX commands, but surely they should be rendered properly in the HTML version of the documentation? However this could be a limitation of GAPDoc that is not easy to overcome, but I think it's worth investigating at least. Here's an example of what I see in the `master` branch:

![screen shot 2018-11-13 at 09 06 39](https://user-images.githubusercontent.com/8956868/48399266-7bb2ff00-e723-11e8-882d-489ea853935a.png)

**Comment by james-d-mitchell** [comment]
I agree, any volunteers? @wilfwilson

**Comment by MTWhyte** [comment]
Have taken this up.

**Comment by wilfwilson** [comment]
Great!

**Comment by wilfwilson** [comment]
Thanks for the help @MTWhyte. This was resolved by your PR #575.
