### ISSUE TITLE
Problem in installing semigroups package on windows

### ISSUE THREAD

**Issue by mansurzubairu** [gap-packages/Semigroups#573]

**Comment by alex-konovalov** [comment]
This is quite short description of the problem, by let me try to guess.

If you are trying to load Semigroups included with GAP 4.9.1, it's not loadable because it does not include Windows binaries. We know this and will try to provide a working version soon, see  https://github.com/gap-system/gap/issues/2984.

If you are trying to build it yourself under Cygwin on windows, then please provide further details about the problem.

**Comment by mansurzubairu** [comment]
I have problem in installing the semigroup package on my windows, although
I have already a working GAP 4.10 on my system. Is the installation of
semigroup package done via dos enviroment or through the gap enviroment? or
do we have any executable file that can do this task? I have seen all the
dependence files but i dont know how to go about installing them on my
windows system.

This are the packages (Needed other packages: orb(>=4.8.0), io(>=4.5.1),
digraphs(>=0.12.0), genss(>=1.6.5),
Suggested other packages: gapdoc(>=1.5.1),)

I will be happy if you can be of help to me.
Thanks and yours in anticipation.
M.M Zubairu
Dept Of Math'l Sciences, BUK.

**Comment by alex-konovalov** [comment]
As a quick alternative to use Semigroups from GAP 4.10.0 remotely, you can try GAP in Jupyter notebook running on Binder - click on the red badge opposite to GAP 4.10.0 release at https://github.com/gap-system/try-gap-in-jupyter. This will work well for not too long and not too memory demanding calculations. Remember to copy your results elsewhere, they are not stored in Binder persistently.

**Comment by james-d-mitchell** [comment]
Is this still a problem? Have you tried using the `PackageManager` to install `Semigroups`? See:

https://github.com/gap-packages/PackageManager

**Comment by alex-konovalov** [comment]
I managed to build semigroups under Cygwin for GAP 4.10.1 distribution, but it fails to load because it needs Digraphs, which trips over https://github.com/gap-packages/Digraphs/issues/177

**Comment by james-d-mitchell** [comment]
This can be closed, hopefully when gap-packages/Digraphs#177 is closed.

**Comment by alex-konovalov** [comment]
Should be loadable in GAP 4.10.2 distribution!
