### ISSUE TITLE
Method installed for Matrix matches more than one declaration

### ISSUE THREAD

**Issue by dimpase** [gap-packages/Semigroups#615]
This is `#I` message printed on vanilla GAP 4.10.2 while loading Semigroups package
(not any of its deps, I checked):
```
gap> LoadPackage("semigroups");
#I  method installed for Matrix matches more than one declaration
...
```
How innocent is this?

**Comment by james-d-mitchell** [comment]
From one perspective, it is innocent, in that I believe that the Semigroups package works just fine, and there are no bugs (that I'm aware of) directly linked to this warning. From another perspective, it is not so innocent, although maybe not in the sense you meant it, and is discussed in some depth in Issue #512.

**Comment by dimpase** [comment]
How does one suppress it with `SetInfoLevel()`, if it's at all possible?
