### ISSUE TITLE
Migrate OnPosIntSetsTrans from GAP to here?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/Semigroups#623]
The GAP kernel implements an undocumented function `OnPosIntSetsTrans` which nothing in GAP itself uses, except some tests for it. The only place using it that we could find is in the Semigroups package.

Perhaps this function and its tests should be migrated to Semigroups then? Of course a little care has to be taken in order to get a smooth migration; I imagine that it would be implemented in the Semigroups kernel code under a different name, and then in the GAP code, there'd be something like `if not IsBound(OnPosIntSetsTrans) then BindGlobal("OnPosIntSetsTrans", WHATEVEr_THE_NEW_NAME_IS); fi;`. That way, 100% performance plus 100% compatibility with both old and new GAP versions.

**Comment by james-d-mitchell** [comment]
@fingolfin I'm happy to do this. The code only exists in the GAP library because at some point in the distant past Semigroups had no kernel module, and this function is critical to the performance of some methods in Semigroups, and so it was agreed at the time to put it into the GAP kernel.

**Comment by james-d-mitchell** [comment]
I will do this tomorrow afternoon unless someone beats me to it.

**Comment by wilfwilson** [comment]
We've decided not to do this for now, see especially #625.
