### ISSUE TITLE
The Travis jobs involving external libsemigroups are failing

### ISSUE THREAD

**Issue by wilfwilson** [gap-packages/Semigroups#628]
See e.g. https://travis-ci.org/gap-packages/Semigroups/jobs/618593823

I have no idea why.

**Comment by wilfwilson** [comment]
Ah, I presume this something to do with the release of libsemigroups `1.0.0` and `1.0.1`. Hope you can sort it out soon @james-d-mitchell.

**Comment by james-d-mitchell** [comment]
Oh yes, the external libsemigroups is installed with conda which now uses version 1.0.2, which is not compatible with the release or master branch of semigroups. I'll try to fix this later today.
