### ISSUE TITLE
Compute `NonTrivialCongurenceClasses` in cases where `CongurenceClasses` can be computed

### ISSUE THREAD

**Issue by reiniscirpons** [gap-packages/Semigroups#677]
Currently 
`gap> NonTrivialCongruenceClasses(CongruencesOfSemigroup(FreeBand(2))[1]);`
Leads to an error, see #676 . Yet Calling
`gap> CongruenceClasses(CongruencesOfSemigroup(FreeBand(2))[1]);`
produces congruence classes with no problems.

It would be nice to make it so that if `CongurenceClasses` could be computed then `NonTrivialCongurenceClasses` could be too.

**Comment by james-d-mitchell** [comment]
Resolved in v3.3.2
